### ISSUE TITLE
cert block to be able to take .pem file

### ISSUE THREAD

**Issue by petelah** [simonmittag/j8a#192]
It would be great if the cert block could take a .pem file as input instead of having to insert the contents of the .pem file. This is hard to manage if we are taking certs from secret stores or other locations and the certificate or private key does not get placed into the yaml file with the correct formatting indentation.

```
cert: path/to/cert_chain.pem
```

**Comment by simonmittag** [comment]
see: https://github.com/simonmittag/j8a/issues/197
