### ISSUE TITLE
Introduce boolean flag to remove X-Request-Info log level increase from production servers

### ISSUE THREAD

**Issue by simonmittag** [simonmittag/j8a#263]
# Why?
An attacker could increase the load on a running J8a instance by sending a large amount of requests with "X-Request-Info: true" header. 

# What?
Introduce a flag to disable this behaviour and ignore the header.

# How?

- [x] introduce a server global flag to disable the parsing of this header. 
- [x] defaults to on (it's useful and doesn't harm normally. Also if someone really tried to send a lot of traffic that would be noticeable before logging becomes an issue. Biggest impact is really performance, but the server never becomes unstable)
- [x] current levels for INFO upgrade are ok, let's keep it simple

**Comment by intermernet** [comment]
Hi Simon,

Some random thoughts on this:

- Should this be a global config variable, or per connection or route?
- Should it default to off?
- Should there be separate flags for debug and info?

Mike.

**Comment by simonmittag** [comment]
@intermernet I updated the section above on how. Are you ok to use your current fork to make a PR?

**Comment by simonmittag** [comment]
i'll fix this one
